name: Plugin_Minecraft_Party
version: 0.1
author: Zarten
main: fr.zarten.pluginminecraftparty.Plugin_Minecraft_Party
commands:
  ping:
    description: Command ping/pong 1
    permission: ping.use
  alert:
    description: Broadcast
    permission: broadcast.use
  gamestart:
    description: Debut de partie, TP tout le monde
  gamestop:
    description: Fin de la partie
  createteam:
    description: cree une equipe
    